name: Build Release

on:
  push:
    branches:
      - 'master'



jobs:
  buildWin:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        cache: pip
    - name: Update pip and install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Bundle With PyInstaller
      run: pyinstaller --onefile ZappyOSC.py
    - name: Archive production artifacts
      uses: actions/upload-artifact@v3
      with:
        name: Upload Artfact
        path: dist
        