name: Build Release

on:
  push:
    branch:
      - 'master'



jobs:
  buildWin:
    runs-on: windows-latest

    steps:
      # used to checkout different branches
      - uses: actions/checkout@v2
        with:
          # checkout my specific branch
          ref: master
      - uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - name: pip install dependencies
        run: pip install -r requirements.txt
      - name: PyInstaller
        run: pyinstaller --onefile ZappyOSC.py    
      - name: Archive production artifacts
        uses: actions/upload-artifact@v3
        with:
          name: ZappyOSC
          path: dist/ZappyOSC.exe
