name: Octo Organization CI

on:
  push:
    branches: 
    - 'releases/**'


jobs:
  buildWin:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v3
      - name: Setup Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: '3.11' 
      - name: Upgrade Pip
      - run: python -m pip install --upgrade pip
      - name: Install Requirements
      - run: python -m pip install -r requirements.txt

      - name: Build into exe with PyInstaller
      - run: pyinstaller --onefile .\ZappyOSC.py

      - uses: actions/upload-artifact@v3
        with:
          name: ZappyOSC
          path: dist/ZappyOSC.exe
